---
# Source: zookeeper-operator/templates/webhookSecretAndConfigurations.yaml
## We generate one root CA and server certificate which are as
  ## by the webhook caBundle and server secrete. We place the both
  ## secret and webhook config files here so they share the same root CA
  ## See https://github.com/helm/helm/issues/6456#issuecomment-701727623---
kind: Secret
apiVersion: v1
type: kubernetes.io/tls
metadata:
  name: zookeeper-operator-default-webhook-secret
  namespace: zookeeper-operator
  labels:
    helm.sh/chart: zookeeper-operator-0.1.1
    app.kubernetes.io/name: zookeeper-operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "0.1.1"
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQrRENDQXVDZ0F3SUJBZ0lRUkttRy9HMEE1U3d0WUhUWGJLQm9DekFOQmdrcWhraUc5dzBCQVFzRkFEQVoKTVJjd0ZRWURWUVFERXc1M1pXSnZiMnN0Y205dmRDMWpZVEFlRncweU1UQTNNVFF3T0RFeE1EUmFGdzB6TVRBMwpNVEl3T0RFeE1EUmFNRFV4TXpBeEJnTlZCQU1US25wdmIydGxaWEJsY2kxdmNHVnlZWFJ2Y2kxa1pXWmhkV3gwCkxYZGxZbWh2YjJzdGMyVnlkbWxqWlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQU1ndlMySkp4UENEMFFSZDM1UFMyYjZVSDhtQ2syMDYzQU11d2l1RUp5clBiNEVFOFdNOWt2d1k3cWV6ZHVQbApIK0JrTzFvK3dRaXd0bUJVeFJpZ0hTREVWeHlIVHlrUDAwK3pKeDF2aGFZUEM0czNZc0t3bWFkWEhTWVVPNW5VClU2em9wdHNZV1A0WU9BNHRpZ0RVSVFyUXQ4bFdSMmFpWXVtQ3pHbndRbmZybnd2NkZycG1UUkRLS1dmblFwek8KYVJBM3YxelArOE1HS0E4OVRObklTNE1aemZxMy8vVlA5ejR5cExKMmE0bHh3a0lhNStKUm5qby9GamhxNEdUSgp1Y3ZReU5WNGwydEVuN2t3WWhnNkVxZk42aXVoRGdGeHV1ZG1JWlJqZkgyZlJJY3piUEZlaEpaa1JFWXNGcDhBCnE3OVNpYm5tMjF6TUU5ajNIT09NOC84Q0F3RUFBYU9DQVI0d2dnRWFNQTRHQTFVZER3RUIvd1FFQXdJRm9EQWQKQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVgpIU01FR0RBV2dCVG1iVEV1SllxWkJJZTNNL3V3MlZxSk9mM3YvVENCdVFZRFZSMFJCSUd4TUlHdWdpcDZiMjlyClpXVndaWEl0YjNCbGNtRjBiM0l0WkdWbVlYVnNkQzEzWldKb2IyOXJMWE5sY25acFkyV0NQWHB2YjJ0bFpYQmwKY2kxdmNHVnlZWFJ2Y2kxa1pXWmhkV3gwTFhkbFltaHZiMnN0YzJWeWRtbGpaUzU2YjI5clpXVndaWEl0YjNCbApjbUYwYjNLQ1FYcHZiMnRsWlhCbGNpMXZjR1Z5WVhSdmNpMWtaV1poZFd4MExYZGxZbWh2YjJzdGMyVnlkbWxqClpTNTZiMjlyWldWd1pYSXRiM0JsY21GMGIzSXVjM1pqTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDWjNnQ1UKdmsvbU92S1FFT0hjbDA4Z2gwYUNjK2hPVFhGTW1qZ0FzM1NRV2pObm0vaklwTzdRd0FPSGF2YnBYU0JqdGd5SApIQjNSVmFFSVlpWXRYS1NBWU5abWd5YjdTR3NpeE9tVGFINngwWm5qVitlMS9WbUpLWnJwS0tSNUNmWUdKUjBOCkFMQUJXUkNhdktnWEJQSXFySHVQTCtkVm94TXJpTXZtU1MwU091cjN5Qm1GSGM1WE5nYzNteUxKSFdkVWtLcncKRlg4Y290UEZVVmFoT0JNK0lHWkp5czZ5ak5Ham5OdUlzN3B0MGQ2WFhBU2Q0aEZ4R2NJZTlrNHpaT0hEcEYxbgpYQks1bnNXdW8rbStkc21XYUYzNVF3MXlMUEN0d0k0S043YytrcVQ5VVBMV2tKTmNlRUVseU83T2I3VktUT3lLCko3MWFoNEIxdkluakU5QmcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeUM5TFlrbkU4SVBSQkYzZms5TFp2cFFmeVlLVGJUcmNBeTdDSzRRbktzOXZnUVR4Cll6MlMvQmp1cDdOMjQrVWY0R1E3V2o3QkNMQzJZRlRGR0tBZElNUlhISWRQS1EvVFQ3TW5IVytGcGc4TGl6ZGkKd3JDWnAxY2RKaFE3bWRSVHJPaW0yeGhZL2hnNERpMktBTlFoQ3RDM3lWWkhacUppNllMTWFmQkNkK3VmQy9vVwp1bVpORU1vcForZENuTTVwRURlL1hNLzd3d1lvRHoxTTJjaExneG5OK3JmLzlVLzNQaktrc25acmlYSENRaHJuCjRsR2VPajhXT0dyZ1pNbTV5OURJMVhpWGEwU2Z1VEJpR0RvU3A4M3FLNkVPQVhHNjUyWWhsR044Zlo5RWh6TnMKOFY2RWxtUkVSaXdXbndDcnYxS0p1ZWJiWE13VDJQY2M0NHp6L3dJREFRQUJBb0lCQVFDc1kzWUNkVTZBWkxONQpsREYyQmt4Mi91NEV4VXFaOU9jRVlwN1poSnVLRlVxTGk2c244QjJFdFIvSUVSY2dGKzhFZUt4WUFkU1AzRVdoCjNUNUIvNWcxNEg2MzFab0kzVlQydkd2QndJa1NRTUNMS2E0RnhMajlUMXFOc1R6R012Ky8xalhpVlN4RjNLdGgKSWp4R2pHYkwvb05XZ2ROSkFpdzF0T3E5akNaaFIyRkNjOWFOcjJTTDdER3NXYjdPRDJIY2ZoWnMvVWtibkNZdQo1bHBkNXhBT0w2Qndzc1pHaTFXa3FtYWVWRVhTNi9mbzlCTmcvL0pKVWFoWXRlQXJlN2creTkwd2RFNzlUUFRLCjdzNU82bUIvck5xRTYzMTdSZm1XSmNSMmw5alR3eXNaL3dWNFdtYUkyM2lUUmsxc0dQWkczNGd4YVJ4dU02aWEKNTdOWldYc0pBb0dCQU1oRUdBQUJmUEp6RzdobXpMdTF0ZkpxZ2hualNjcTJZbmRCeU45N0dwNFdEelBWeHRvVgpud3F0V21JdnFoRTRNNHRpOU5OSUFHb2N4S2lNblFvMTJLQUtnL3RzR0J3VG15dkt4Q08zOWpWNlZ3QWhLSWowClBmbTV1RGFvcWczZHRaNmJGL2FtVHRPdENtTW55UkVSNGt6TnJGT1FVa0cvVjloeU9lWTJ0YUkxQW9HQkFQL2wKYVlzdjVGS01xS3M4UStMRFJPWVd6b0VUeGZNWjdKNEtrMHhaMVAzTnBHWGc4UDFDNGR6TFJNWWtxK3RqU0tTNAptZ1B4RGNCaHMwMThmZ01hSUY4dmpvdzFrcm0wbjZRWWJhVHFEcnRIazZ2NXRKLzNCTmJORjVCSHVpMjlEb1NDClZ3OFMrVTVtditrd2YrNWlTSHg1YUxVTWtRN2lOeCtkbG1Fa0tZUGpBb0dBRHMxWnFNWnpZY2c0U0V6dzNQNzEKVDlHbmhCcFVuZk1WSEJOMHNXLzc2NnRkdkVzVXc1SE5pNUI4bWIxRUtMbXF0YWEreWM4TW1Ncy9qZVcyeGNadApHSWN1Y2lydkxVUVZ1QXJvckdzd2U0dHJXc3NZbitiTm5lT29SZ0g1YjhUdlk2VzdBN1FQSjM0bXdtVnlheHlUClNYSDZSc0xvRVl2L0JqU0xLd1RvTC9FQ2dZRUE1VWRJS2MzZlpaZGlDUXNXU0RkdHBEc0xDOXdMb0tXNXZHRDkKV1l1anEwUjE2RktEbW1neXR3SHB2UjllYXFtcWpPeGFFdTRJeERiRjBNZWFvR3pvVkdEbjkvaUlYcHZYN2M5MQpiaTNJeFVSOHE3b3dmS04zVW42d2ZqWEdPdlVKN1BCYjBNWFBXcy8xWTVweEJjWko3RDFiODl3dW5JZFRuS0ExCi9SUEpuc0VDZ1lBMjV0VmZlL0d3SlZBK09vQnJVZnUwcVFKRWZYNXE3NzYremVRaDZ5SWRRemtMeGtOT3g5UDAKZ0FmaUJqOUx0enQxM21KMUV1aUVqZnpDditSL1pCWERjLzBRVVVOVi9RTGFOVE1iSlQ1K3cwcHVBbklqTkxrTgp0MkVwRVdCRTFIQVdkVFdTV3FRdkkxVFBTWnEvWHpSeEdQTHgrRXY4UjFEVEdieGc0MWNwUFE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
# Source: zookeeper-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zookeeper-operator-manager-role
  labels:
    helm.sh/chart: zookeeper-operator-0.1.1
    app.kubernetes.io/name: zookeeper-operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "0.1.1"
rules:
  - apiGroups:
      - zookeeper.monime.sl
    resources:
      - zookeeperclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - zookeeper.monime.sl
    resources:
      - zookeeperclusters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
      - apps
      - batch
      - policy
      - extensions
    resources:
      - jobs
      - pods
      - events
      - secrets
      - services
      - configmaps
      - statefulsets
      - poddisruptionbudgets
      - persistentvolumeclaims
    verbs:
      - '*'
---
# Source: zookeeper-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zookeeper-operator-manager-role-binding
  labels:
    helm.sh/chart: zookeeper-operator-0.1.1
    app.kubernetes.io/name: zookeeper-operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "0.1.1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zookeeper-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: zookeeper-operator
---
# Source: zookeeper-operator/templates/role.yaml
# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zookeeper-operator-leader-election-role
  namespace: zookeeper-operator
  labels:
    helm.sh/chart: zookeeper-operator-0.1.1
    app.kubernetes.io/name: zookeeper-operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "0.1.1"
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
# Source: zookeeper-operator/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zookeeper-operator-leader-election-role-binding
  namespace: zookeeper-operator
  labels:
    helm.sh/chart: zookeeper-operator-0.1.1
    app.kubernetes.io/name: zookeeper-operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "0.1.1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zookeeper-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: zookeeper-operator
---
# Source: zookeeper-operator/templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-operator-default-webhook-service
  namespace: zookeeper-operator
  labels:
    helm.sh/chart: zookeeper-operator-0.1.1
    app.kubernetes.io/name: zookeeper-operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "0.1.1"
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app.kubernetes.io/name: zookeeper-operator
    app.kubernetes.io/instance: default
---
# Source: zookeeper-operator/templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-operator-controller-manager-metrics-service
  namespace: zookeeper-operator
  labels:
    helm.sh/chart: zookeeper-operator-0.1.1
    app.kubernetes.io/name: zookeeper-operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "0.1.1"
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  
  selector:
    app.kubernetes.io/name: zookeeper-operator
    app.kubernetes.io/instance: default
---
# Source: zookeeper-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-zookeeper-operator
  namespace: zookeeper-operator
  labels:
    helm.sh/chart: zookeeper-operator-0.1.1
    app.kubernetes.io/name: zookeeper-operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "0.1.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper-operator
      app.kubernetes.io/instance: default
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zookeeper-operator
        app.kubernetes.io/instance: default
    spec:
      containers:
        - name: zookeeper-operator
          image: monime/zookeeper-operator:v0.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: webhook-certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsUser: 65534
          env:
            - name: LEADER_ELECTION_NAMESPACE
              value: zookeeper-operator
      volumes:
        - name: webhook-certs
          secret:
            secretName: zookeeper-operator-default-webhook-secret
      terminationGracePeriodSeconds: 20
---
# Source: zookeeper-operator/templates/webhookSecretAndConfigurations.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIVENDQWdXZ0F3SUJBZ0lRYVRiRjdOemxBeGxzWEZhL3c1S2I5ekFOQmdrcWhraUc5dzBCQVFzRkFEQVoKTVJjd0ZRWURWUVFERXc1M1pXSnZiMnN0Y205dmRDMWpZVEFlRncweU1UQTNNVFF3T0RFeE1EUmFGdzB6TVRBMwpNVEl3T0RFeE1EUmFNQmt4RnpBVkJnTlZCQU1URG5kbFltOXZheTF5YjI5MExXTmhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFyNERWVHdIbmN0aDUzcGdUc2tlSGNOdXB4MUR6RlFUeW14d0kKbWJTM2JQU01JKzY1bUNzbzNSRTl0ay8wWitBQmlOdEM1WkNCTmlBTlhjLyt1T3FBa0xmbEcvL3ZreTNDc1VmZgozSEcvVm9EMGdGdEpqYUYvVzdlQWMrTmJjMnA2enJZdDFoamQ1TWpsWDZGaGt0SW1rZ0w5MXpsNW8xNVQxN2hnCm5Tb0xHdURidGx2a2N0U3FBQXRjalgrOFlzdjJrWnVvNkVMdytPV0RXU1Jrc2Y3b1F2TEsrSVhrTk95WVhtVUoKUTF6QUUzRUpET2VSMkl1RjFLN1Q4Vlp0ZkdXcjNKanNXL2d2aTlhaC9rMkRpVEhzRitpcUw1Mk83a0ZORHllNQo4L0JLM05OKzFVLytxUjZlUy95aU12Q1p2WktEU0pIOGdBQzhnUVhHQXJxNFpnVnkvd0lEQVFBQm8yRXdYekFPCkJnTlZIUThCQWY4RUJBTUNBcVF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGT1p0TVM0bGlwa0VoN2N6KzdEWldvazUvZS85TUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQkFRQmhvSHpyRkJNVWY5MUZpMWJPOXZCRzBSSTFHZ0lWdFNpVXQzeTQ5alRXClFzcUtIWnpxNkgyOHBRbGZXb0xwUHpzeC9RTnMwSkh2U2s4NnNGdzRBVDlsZnpmY1NNNmhMQWFUcEZvTG1sMzYKV1E2N052WnR4RmNEVXdoMWwxdkZZVEdYN2luWTlheVZzZEJuNnIyUzdzekwvUDRCalhNdzZxcGc1QnFLa3hjMAo0T1dIMTlxYU43R2xST0Q1NlFjRzZpR3NTK0JGMTc0cG0zamQ1ZThZK0lPZlJieElTUUtNRW1EUGVhOXU3SlBCCnB0Q0dodlN5dVkraG1kcVllMmkraXNWUWVSRmJXNnV3TlRzcWRzL1Y3Zk5VaGpGUGlieG9tdnF5YkxjWERld2wKc3VFY2Jqb1ptRHhYYU5sb3p0VTlIWndjRW80TTdnZk1pb0lIOFIvUHdmMXoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: zookeeper-operator-default-webhook-service
      namespace: zookeeper-operator
      path: /mutate-zookeeper-monime-sl-v1alpha1-zookeepercluster
  failurePolicy: Fail
  name: mzookeepercluster.kb.io
  rules:
  - apiGroups:
    - zookeeper.monime.sl
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - zookeeperclusters
  sideEffects: None
---
# Source: zookeeper-operator/templates/webhookSecretAndConfigurations.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIVENDQWdXZ0F3SUJBZ0lRYVRiRjdOemxBeGxzWEZhL3c1S2I5ekFOQmdrcWhraUc5dzBCQVFzRkFEQVoKTVJjd0ZRWURWUVFERXc1M1pXSnZiMnN0Y205dmRDMWpZVEFlRncweU1UQTNNVFF3T0RFeE1EUmFGdzB6TVRBMwpNVEl3T0RFeE1EUmFNQmt4RnpBVkJnTlZCQU1URG5kbFltOXZheTF5YjI5MExXTmhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFyNERWVHdIbmN0aDUzcGdUc2tlSGNOdXB4MUR6RlFUeW14d0kKbWJTM2JQU01JKzY1bUNzbzNSRTl0ay8wWitBQmlOdEM1WkNCTmlBTlhjLyt1T3FBa0xmbEcvL3ZreTNDc1VmZgozSEcvVm9EMGdGdEpqYUYvVzdlQWMrTmJjMnA2enJZdDFoamQ1TWpsWDZGaGt0SW1rZ0w5MXpsNW8xNVQxN2hnCm5Tb0xHdURidGx2a2N0U3FBQXRjalgrOFlzdjJrWnVvNkVMdytPV0RXU1Jrc2Y3b1F2TEsrSVhrTk95WVhtVUoKUTF6QUUzRUpET2VSMkl1RjFLN1Q4Vlp0ZkdXcjNKanNXL2d2aTlhaC9rMkRpVEhzRitpcUw1Mk83a0ZORHllNQo4L0JLM05OKzFVLytxUjZlUy95aU12Q1p2WktEU0pIOGdBQzhnUVhHQXJxNFpnVnkvd0lEQVFBQm8yRXdYekFPCkJnTlZIUThCQWY4RUJBTUNBcVF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGT1p0TVM0bGlwa0VoN2N6KzdEWldvazUvZS85TUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQkFRQmhvSHpyRkJNVWY5MUZpMWJPOXZCRzBSSTFHZ0lWdFNpVXQzeTQ5alRXClFzcUtIWnpxNkgyOHBRbGZXb0xwUHpzeC9RTnMwSkh2U2s4NnNGdzRBVDlsZnpmY1NNNmhMQWFUcEZvTG1sMzYKV1E2N052WnR4RmNEVXdoMWwxdkZZVEdYN2luWTlheVZzZEJuNnIyUzdzekwvUDRCalhNdzZxcGc1QnFLa3hjMAo0T1dIMTlxYU43R2xST0Q1NlFjRzZpR3NTK0JGMTc0cG0zamQ1ZThZK0lPZlJieElTUUtNRW1EUGVhOXU3SlBCCnB0Q0dodlN5dVkraG1kcVllMmkraXNWUWVSRmJXNnV3TlRzcWRzL1Y3Zk5VaGpGUGlieG9tdnF5YkxjWERld2wKc3VFY2Jqb1ptRHhYYU5sb3p0VTlIWndjRW80TTdnZk1pb0lIOFIvUHdmMXoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: zookeeper-operator-default-webhook-service
      namespace: zookeeper-operator
      path: /validate-zookeeper-monime-sl-v1alpha1-zookeepercluster
  failurePolicy: Fail
  name: vzookeepercluster.kb.io
  rules:
  - apiGroups:
    - zookeeper.monime.sl
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - zookeeperclusters
  sideEffects: None
