---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /mutate-zookeeper-monime-sl-v1alpha1-zookeepercluster
    failurePolicy: Fail
    name: mzookeepercluster.kb.io
    rules:
      - apiGroups:
          - zookeeper.monime.sl
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - zookeeperclusters
    sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-zookeeper-monime-sl-v1alpha1-zookeepercluster
    failurePolicy: Fail
    name: vzookeepercluster.kb.io
    rules:
      - apiGroups:
          - zookeeper.monime.sl
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - zookeeperclusters
    sideEffects: None
