run:
  timeout: 10m
linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gomodguard
    - gosimple
    - importas
    - ineffassign
    - makezero
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - staticcheck
    - stylecheck
    - tenv
    - typecheck
    - unconvert
    - unused
    - whitespace
  fast: false
issues:
  exclude:
    - "SA1019"
    - "ST1003"
    - "regexpMust"
output:
  staticcheck:
    checks: [ "all" ]
  stylecheck:
    checks: [ "all" ]
  gosec:
    severity: "high"
    confidence: "high"