# permissions for end users to view zookeeperclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zookeepercluster-viewer-role
rules:
- apiGroups:
  - zookeeper.skulup.com
  resources:
  - zookeeperclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zookeeper.skulup.com
  resources:
  - zookeeperclusters/status
  verbs:
  - get
